/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Contact } from "./models/contact-model";
export namespace Components {
    interface AppRoot {
    }
    interface ContactList {
    }
    interface ContactRow {
        "contact": Contact;
        "deleteHandler": any;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLContactListElement extends Components.ContactList, HTMLStencilElement {
    }
    var HTMLContactListElement: {
        prototype: HTMLContactListElement;
        new (): HTMLContactListElement;
    };
    interface HTMLContactRowElement extends Components.ContactRow, HTMLStencilElement {
    }
    var HTMLContactRowElement: {
        prototype: HTMLContactRowElement;
        new (): HTMLContactRowElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "contact-list": HTMLContactListElement;
        "contact-row": HTMLContactRowElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ContactList {
    }
    interface ContactRow {
        "contact"?: Contact;
        "deleteHandler"?: any;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "contact-list": ContactList;
        "contact-row": ContactRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "contact-list": LocalJSX.ContactList & JSXBase.HTMLAttributes<HTMLContactListElement>;
            "contact-row": LocalJSX.ContactRow & JSXBase.HTMLAttributes<HTMLContactRowElement>;
        }
    }
}
