//2. action type list
const INCREASE_VALUE_ACTION = 'INCREASE_VALUE'
const DECREASE_VALUE_ACTION = 'DECREASE_VALUE'
const UPDATE_NAME_ACTION = 'UPDATE_NAME'
const GET_CONTACTS_SUCCESS_ACTION = 'GET_CONTACTS_SUCCESS'
const GET_CONTACTS_FAILURE_ACTION = 'GET_CONTACTS_FAILURE'

module.exports = {
    INCREASE_VALUE_ACTION,
    DECREASE_VALUE_ACTION,
    UPDATE_NAME_ACTION,
    GET_CONTACTS_SUCCESS_ACTION,
    GET_CONTACTS_FAILURE_ACTION
}