//2. action type list
const INCREASE_VALUE_ACTION = 'INCREASE_VALUE'
const DECREASE_VALUE_ACTION = 'DECREASE_VALUE'
const UPDATE_NAME_ACTION = 'UPDATE_NAME'

module.exports = {
    INCREASE_VALUE_ACTION,
    DECREASE_VALUE_ACTION,
    UPDATE_NAME_ACTION
}